server:
  port: 8888
#  servlet:
#    session:
#      cookie:
#        domain:
spring:
  # 设置时区
  jackson:
    time-zone: GMT+8
  profiles:
    active: dev
  main:
    allow-circular-references: true
  # DataSource Config
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${sql.url}
      username: ${sql.username}
      password: ${sql.password}
      # 超过时间限制是否回收
      remove-abandoned: true
      # 超时时间；单位为秒。1800秒=30分钟
      remove-abandoned-timeout: 1800
      initialSize: 0
      minIdle: 5
      maxActive: 20
      maxWait: 600000
  # session 失效时间（分钟）
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: ${redis.host}
    database: 0
    password: ${redis.password}
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    sql: error

